// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/collector-protocol/DirectionBoard.tsx": () => import("../components/mockups/collector-protocol/DirectionBoard.tsx"),
  "./components/mockups/hybrid/DirectionBoard.tsx": () => import("../components/mockups/hybrid/DirectionBoard.tsx"),
  "./components/mockups/obsidian-cockpit/DirectionBoard.tsx": () => import("../components/mockups/obsidian-cockpit/DirectionBoard.tsx"),
  "./components/mockups/my-syndicate-cockpit/Cockpit.tsx": () => import("../components/mockups/my-syndicate-cockpit/Cockpit.tsx")
};
