#!/bin/bash
set -e

# Post-merge setup for The Syndicate.
# Runs automatically after a task is merged. Keep it idempotent, non-interactive,
# and fast. This project uses Bun and reads protocol state from on-chain (no local
# database / migrations), so the only reconciliation needed is dependency sync.
# TanStack route-tree codegen is regenerated by the dev workflow on restart.

echo "[post-merge] syncing dependencies with bun install..."
bun install

echo "[post-merge] done."
