/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as TokenomicsRouteImport } from './routes/tokenomics'
import { Route as TokenRouteImport } from './routes/token'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as RanksRouteImport } from './routes/ranks'
import { Route as ProtocolHealthRouteImport } from './routes/protocol-health'
import { Route as NftsRouteImport } from './routes/nfts'
import { Route as NftRouteImport } from './routes/nft'
import { Route as MySyndicateRouteImport } from './routes/my-syndicate'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LiquidityRouteImport } from './routes/liquidity'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as JoinRouteImport } from './routes/join'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EpisodesRouteImport } from './routes/episodes'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChronicleRouteImport } from './routes/chronicle'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletAddressRouteImport } from './routes/wallet.$address'
import { Route as MilestoneIdRouteImport } from './routes/milestone.$id'
import { Route as LabsInvariantsRouteImport } from './routes/labs.invariants'
import { Route as LabsDesignArchiveRouteImport } from './routes/labs.design-archive'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as XTxHashRouteImport } from './routes/x.tx.$hash'
import { Route as ApiPublicProtocolHealthRouteImport } from './routes/api/public/protocol-health'
import { Route as ApiOgHealthRouteImport } from './routes/api/og/health'
import { Route as ApiPublicProtocolHealthCsvRouteImport } from './routes/api/public/protocol-health.csv'
import { Route as ApiPublicIndexerHealthRouteImport } from './routes/api/public/indexer/health'
import { Route as ApiPublicOgWalletAddressRouteImport } from './routes/api/public/og/wallet.$address'
import { Route as ApiPublicOgMilestoneIdRouteImport } from './routes/api/public/og/milestone.$id'

const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenomicsRoute = TokenomicsRouteImport.update({
  id: '/tokenomics',
  path: '/tokenomics',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const RanksRoute = RanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolHealthRoute = ProtocolHealthRouteImport.update({
  id: '/protocol-health',
  path: '/protocol-health',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsRoute = NftsRouteImport.update({
  id: '/nfts',
  path: '/nfts',
  getParentRoute: () => rootRouteImport,
} as any)
const NftRoute = NftRouteImport.update({
  id: '/nft',
  path: '/nft',
  getParentRoute: () => rootRouteImport,
} as any)
const MySyndicateRoute = MySyndicateRouteImport.update({
  id: '/my-syndicate',
  path: '/my-syndicate',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidityRoute = LiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesRoute = EpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleRoute = ChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletAddressRoute = WalletAddressRouteImport.update({
  id: '/wallet/$address',
  path: '/wallet/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestoneIdRoute = MilestoneIdRouteImport.update({
  id: '/milestone/$id',
  path: '/milestone/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsInvariantsRoute = LabsInvariantsRouteImport.update({
  id: '/invariants',
  path: '/invariants',
  getParentRoute: () => LabsRoute,
} as any)
const LabsDesignArchiveRoute = LabsDesignArchiveRouteImport.update({
  id: '/design-archive',
  path: '/design-archive',
  getParentRoute: () => LabsRoute,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ChaptersRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const XTxHashRoute = XTxHashRouteImport.update({
  id: '/x/tx/$hash',
  path: '/x/tx/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProtocolHealthRoute = ApiPublicProtocolHealthRouteImport.update({
  id: '/api/public/protocol-health',
  path: '/api/public/protocol-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgHealthRoute = ApiOgHealthRouteImport.update({
  id: '/api/og/health',
  path: '/api/og/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProtocolHealthCsvRoute =
  ApiPublicProtocolHealthCsvRouteImport.update({
    id: '/csv',
    path: '/csv',
    getParentRoute: () => ApiPublicProtocolHealthRoute,
  } as any)
const ApiPublicIndexerHealthRoute = ApiPublicIndexerHealthRouteImport.update({
  id: '/api/public/indexer/health',
  path: '/api/public/indexer/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgWalletAddressRoute =
  ApiPublicOgWalletAddressRouteImport.update({
    id: '/api/public/og/wallet/$address',
    path: '/api/public/og/wallet/$address',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOgMilestoneIdRoute = ApiPublicOgMilestoneIdRouteImport.update({
  id: '/api/public/og/milestone/$id',
  path: '/api/public/og/milestone/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/archive': typeof ArchiveRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/chronicle': typeof ChronicleRoute
  '/docs': typeof DocsRoute
  '/episodes': typeof EpisodesRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/join': typeof JoinRoute
  '/labs': typeof LabsRouteWithChildren
  '/liquidity': typeof LiquidityRoute
  '/members': typeof MembersRoute
  '/my-syndicate': typeof MySyndicateRoute
  '/nft': typeof NftRoute
  '/nfts': typeof NftsRoute
  '/protocol-health': typeof ProtocolHealthRoute
  '/ranks': typeof RanksRoute
  '/referral': typeof ReferralRoute
  '/registry': typeof RegistryRoute
  '/risk': typeof RiskRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/token': typeof TokenRoute
  '/tokenomics': typeof TokenomicsRoute
  '/transparency': typeof TransparencyRoute
  '/vault': typeof VaultRoute
  '/whitepaper': typeof WhitepaperRoute
  '/api/chat': typeof ApiChatRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/labs/design-archive': typeof LabsDesignArchiveRoute
  '/labs/invariants': typeof LabsInvariantsRoute
  '/milestone/$id': typeof MilestoneIdRoute
  '/wallet/$address': typeof WalletAddressRoute
  '/api/og/health': typeof ApiOgHealthRoute
  '/api/public/protocol-health': typeof ApiPublicProtocolHealthRouteWithChildren
  '/x/tx/$hash': typeof XTxHashRoute
  '/api/public/indexer/health': typeof ApiPublicIndexerHealthRoute
  '/api/public/protocol-health/csv': typeof ApiPublicProtocolHealthCsvRoute
  '/api/public/og/milestone/$id': typeof ApiPublicOgMilestoneIdRoute
  '/api/public/og/wallet/$address': typeof ApiPublicOgWalletAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/archive': typeof ArchiveRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/chronicle': typeof ChronicleRoute
  '/docs': typeof DocsRoute
  '/episodes': typeof EpisodesRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/join': typeof JoinRoute
  '/labs': typeof LabsRouteWithChildren
  '/liquidity': typeof LiquidityRoute
  '/members': typeof MembersRoute
  '/my-syndicate': typeof MySyndicateRoute
  '/nft': typeof NftRoute
  '/nfts': typeof NftsRoute
  '/protocol-health': typeof ProtocolHealthRoute
  '/ranks': typeof RanksRoute
  '/referral': typeof ReferralRoute
  '/registry': typeof RegistryRoute
  '/risk': typeof RiskRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/token': typeof TokenRoute
  '/tokenomics': typeof TokenomicsRoute
  '/transparency': typeof TransparencyRoute
  '/vault': typeof VaultRoute
  '/whitepaper': typeof WhitepaperRoute
  '/api/chat': typeof ApiChatRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/labs/design-archive': typeof LabsDesignArchiveRoute
  '/labs/invariants': typeof LabsInvariantsRoute
  '/milestone/$id': typeof MilestoneIdRoute
  '/wallet/$address': typeof WalletAddressRoute
  '/api/og/health': typeof ApiOgHealthRoute
  '/api/public/protocol-health': typeof ApiPublicProtocolHealthRouteWithChildren
  '/x/tx/$hash': typeof XTxHashRoute
  '/api/public/indexer/health': typeof ApiPublicIndexerHealthRoute
  '/api/public/protocol-health/csv': typeof ApiPublicProtocolHealthCsvRoute
  '/api/public/og/milestone/$id': typeof ApiPublicOgMilestoneIdRoute
  '/api/public/og/wallet/$address': typeof ApiPublicOgWalletAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/archive': typeof ArchiveRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/chronicle': typeof ChronicleRoute
  '/docs': typeof DocsRoute
  '/episodes': typeof EpisodesRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/join': typeof JoinRoute
  '/labs': typeof LabsRouteWithChildren
  '/liquidity': typeof LiquidityRoute
  '/members': typeof MembersRoute
  '/my-syndicate': typeof MySyndicateRoute
  '/nft': typeof NftRoute
  '/nfts': typeof NftsRoute
  '/protocol-health': typeof ProtocolHealthRoute
  '/ranks': typeof RanksRoute
  '/referral': typeof ReferralRoute
  '/registry': typeof RegistryRoute
  '/risk': typeof RiskRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/token': typeof TokenRoute
  '/tokenomics': typeof TokenomicsRoute
  '/transparency': typeof TransparencyRoute
  '/vault': typeof VaultRoute
  '/whitepaper': typeof WhitepaperRoute
  '/api/chat': typeof ApiChatRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/labs/design-archive': typeof LabsDesignArchiveRoute
  '/labs/invariants': typeof LabsInvariantsRoute
  '/milestone/$id': typeof MilestoneIdRoute
  '/wallet/$address': typeof WalletAddressRoute
  '/api/og/health': typeof ApiOgHealthRoute
  '/api/public/protocol-health': typeof ApiPublicProtocolHealthRouteWithChildren
  '/x/tx/$hash': typeof XTxHashRoute
  '/api/public/indexer/health': typeof ApiPublicIndexerHealthRoute
  '/api/public/protocol-health/csv': typeof ApiPublicProtocolHealthCsvRoute
  '/api/public/og/milestone/$id': typeof ApiPublicOgMilestoneIdRoute
  '/api/public/og/wallet/$address': typeof ApiPublicOgWalletAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/ai'
    | '/archive'
    | '/chapters'
    | '/chronicle'
    | '/docs'
    | '/episodes'
    | '/faq'
    | '/founders'
    | '/join'
    | '/labs'
    | '/liquidity'
    | '/members'
    | '/my-syndicate'
    | '/nft'
    | '/nfts'
    | '/protocol-health'
    | '/ranks'
    | '/referral'
    | '/registry'
    | '/risk'
    | '/roadmap'
    | '/sitemap.xml'
    | '/token'
    | '/tokenomics'
    | '/transparency'
    | '/vault'
    | '/whitepaper'
    | '/api/chat'
    | '/chapters/$slug'
    | '/labs/design-archive'
    | '/labs/invariants'
    | '/milestone/$id'
    | '/wallet/$address'
    | '/api/og/health'
    | '/api/public/protocol-health'
    | '/x/tx/$hash'
    | '/api/public/indexer/health'
    | '/api/public/protocol-health/csv'
    | '/api/public/og/milestone/$id'
    | '/api/public/og/wallet/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/ai'
    | '/archive'
    | '/chapters'
    | '/chronicle'
    | '/docs'
    | '/episodes'
    | '/faq'
    | '/founders'
    | '/join'
    | '/labs'
    | '/liquidity'
    | '/members'
    | '/my-syndicate'
    | '/nft'
    | '/nfts'
    | '/protocol-health'
    | '/ranks'
    | '/referral'
    | '/registry'
    | '/risk'
    | '/roadmap'
    | '/sitemap.xml'
    | '/token'
    | '/tokenomics'
    | '/transparency'
    | '/vault'
    | '/whitepaper'
    | '/api/chat'
    | '/chapters/$slug'
    | '/labs/design-archive'
    | '/labs/invariants'
    | '/milestone/$id'
    | '/wallet/$address'
    | '/api/og/health'
    | '/api/public/protocol-health'
    | '/x/tx/$hash'
    | '/api/public/indexer/health'
    | '/api/public/protocol-health/csv'
    | '/api/public/og/milestone/$id'
    | '/api/public/og/wallet/$address'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/ai'
    | '/archive'
    | '/chapters'
    | '/chronicle'
    | '/docs'
    | '/episodes'
    | '/faq'
    | '/founders'
    | '/join'
    | '/labs'
    | '/liquidity'
    | '/members'
    | '/my-syndicate'
    | '/nft'
    | '/nfts'
    | '/protocol-health'
    | '/ranks'
    | '/referral'
    | '/registry'
    | '/risk'
    | '/roadmap'
    | '/sitemap.xml'
    | '/token'
    | '/tokenomics'
    | '/transparency'
    | '/vault'
    | '/whitepaper'
    | '/api/chat'
    | '/chapters/$slug'
    | '/labs/design-archive'
    | '/labs/invariants'
    | '/milestone/$id'
    | '/wallet/$address'
    | '/api/og/health'
    | '/api/public/protocol-health'
    | '/x/tx/$hash'
    | '/api/public/indexer/health'
    | '/api/public/protocol-health/csv'
    | '/api/public/og/milestone/$id'
    | '/api/public/og/wallet/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AiRoute: typeof AiRoute
  ArchiveRoute: typeof ArchiveRoute
  ChaptersRoute: typeof ChaptersRouteWithChildren
  ChronicleRoute: typeof ChronicleRoute
  DocsRoute: typeof DocsRoute
  EpisodesRoute: typeof EpisodesRoute
  FaqRoute: typeof FaqRoute
  FoundersRoute: typeof FoundersRoute
  JoinRoute: typeof JoinRoute
  LabsRoute: typeof LabsRouteWithChildren
  LiquidityRoute: typeof LiquidityRoute
  MembersRoute: typeof MembersRoute
  MySyndicateRoute: typeof MySyndicateRoute
  NftRoute: typeof NftRoute
  NftsRoute: typeof NftsRoute
  ProtocolHealthRoute: typeof ProtocolHealthRoute
  RanksRoute: typeof RanksRoute
  ReferralRoute: typeof ReferralRoute
  RegistryRoute: typeof RegistryRoute
  RiskRoute: typeof RiskRoute
  RoadmapRoute: typeof RoadmapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TokenRoute: typeof TokenRoute
  TokenomicsRoute: typeof TokenomicsRoute
  TransparencyRoute: typeof TransparencyRoute
  VaultRoute: typeof VaultRoute
  WhitepaperRoute: typeof WhitepaperRoute
  ApiChatRoute: typeof ApiChatRoute
  MilestoneIdRoute: typeof MilestoneIdRoute
  WalletAddressRoute: typeof WalletAddressRoute
  ApiOgHealthRoute: typeof ApiOgHealthRoute
  ApiPublicProtocolHealthRoute: typeof ApiPublicProtocolHealthRouteWithChildren
  XTxHashRoute: typeof XTxHashRoute
  ApiPublicIndexerHealthRoute: typeof ApiPublicIndexerHealthRoute
  ApiPublicOgMilestoneIdRoute: typeof ApiPublicOgMilestoneIdRoute
  ApiPublicOgWalletAddressRoute: typeof ApiPublicOgWalletAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokenomics': {
      id: '/tokenomics'
      path: '/tokenomics'
      fullPath: '/tokenomics'
      preLoaderRoute: typeof TokenomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranks': {
      id: '/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof RanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol-health': {
      id: '/protocol-health'
      path: '/protocol-health'
      fullPath: '/protocol-health'
      preLoaderRoute: typeof ProtocolHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts': {
      id: '/nfts'
      path: '/nfts'
      fullPath: '/nfts'
      preLoaderRoute: typeof NftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft': {
      id: '/nft'
      path: '/nft'
      fullPath: '/nft'
      preLoaderRoute: typeof NftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-syndicate': {
      id: '/my-syndicate'
      path: '/my-syndicate'
      fullPath: '/my-syndicate'
      preLoaderRoute: typeof MySyndicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidity': {
      id: '/liquidity'
      path: '/liquidity'
      fullPath: '/liquidity'
      preLoaderRoute: typeof LiquidityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes': {
      id: '/episodes'
      path: '/episodes'
      fullPath: '/episodes'
      preLoaderRoute: typeof EpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle': {
      id: '/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof ChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/$address': {
      id: '/wallet/$address'
      path: '/wallet/$address'
      fullPath: '/wallet/$address'
      preLoaderRoute: typeof WalletAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestone/$id': {
      id: '/milestone/$id'
      path: '/milestone/$id'
      fullPath: '/milestone/$id'
      preLoaderRoute: typeof MilestoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/invariants': {
      id: '/labs/invariants'
      path: '/invariants'
      fullPath: '/labs/invariants'
      preLoaderRoute: typeof LabsInvariantsRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/design-archive': {
      id: '/labs/design-archive'
      path: '/design-archive'
      fullPath: '/labs/design-archive'
      preLoaderRoute: typeof LabsDesignArchiveRouteImport
      parentRoute: typeof LabsRoute
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x/tx/$hash': {
      id: '/x/tx/$hash'
      path: '/x/tx/$hash'
      fullPath: '/x/tx/$hash'
      preLoaderRoute: typeof XTxHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/protocol-health': {
      id: '/api/public/protocol-health'
      path: '/api/public/protocol-health'
      fullPath: '/api/public/protocol-health'
      preLoaderRoute: typeof ApiPublicProtocolHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/health': {
      id: '/api/og/health'
      path: '/api/og/health'
      fullPath: '/api/og/health'
      preLoaderRoute: typeof ApiOgHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/protocol-health/csv': {
      id: '/api/public/protocol-health/csv'
      path: '/csv'
      fullPath: '/api/public/protocol-health/csv'
      preLoaderRoute: typeof ApiPublicProtocolHealthCsvRouteImport
      parentRoute: typeof ApiPublicProtocolHealthRoute
    }
    '/api/public/indexer/health': {
      id: '/api/public/indexer/health'
      path: '/api/public/indexer/health'
      fullPath: '/api/public/indexer/health'
      preLoaderRoute: typeof ApiPublicIndexerHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/wallet/$address': {
      id: '/api/public/og/wallet/$address'
      path: '/api/public/og/wallet/$address'
      fullPath: '/api/public/og/wallet/$address'
      preLoaderRoute: typeof ApiPublicOgWalletAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/milestone/$id': {
      id: '/api/public/og/milestone/$id'
      path: '/api/public/og/milestone/$id'
      fullPath: '/api/public/og/milestone/$id'
      preLoaderRoute: typeof ApiPublicOgMilestoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChaptersRouteChildren {
  ChaptersSlugRoute: typeof ChaptersSlugRoute
}

const ChaptersRouteChildren: ChaptersRouteChildren = {
  ChaptersSlugRoute: ChaptersSlugRoute,
}

const ChaptersRouteWithChildren = ChaptersRoute._addFileChildren(
  ChaptersRouteChildren,
)

interface LabsRouteChildren {
  LabsDesignArchiveRoute: typeof LabsDesignArchiveRoute
  LabsInvariantsRoute: typeof LabsInvariantsRoute
}

const LabsRouteChildren: LabsRouteChildren = {
  LabsDesignArchiveRoute: LabsDesignArchiveRoute,
  LabsInvariantsRoute: LabsInvariantsRoute,
}

const LabsRouteWithChildren = LabsRoute._addFileChildren(LabsRouteChildren)

interface ApiPublicProtocolHealthRouteChildren {
  ApiPublicProtocolHealthCsvRoute: typeof ApiPublicProtocolHealthCsvRoute
}

const ApiPublicProtocolHealthRouteChildren: ApiPublicProtocolHealthRouteChildren =
  {
    ApiPublicProtocolHealthCsvRoute: ApiPublicProtocolHealthCsvRoute,
  }

const ApiPublicProtocolHealthRouteWithChildren =
  ApiPublicProtocolHealthRoute._addFileChildren(
    ApiPublicProtocolHealthRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AiRoute: AiRoute,
  ArchiveRoute: ArchiveRoute,
  ChaptersRoute: ChaptersRouteWithChildren,
  ChronicleRoute: ChronicleRoute,
  DocsRoute: DocsRoute,
  EpisodesRoute: EpisodesRoute,
  FaqRoute: FaqRoute,
  FoundersRoute: FoundersRoute,
  JoinRoute: JoinRoute,
  LabsRoute: LabsRouteWithChildren,
  LiquidityRoute: LiquidityRoute,
  MembersRoute: MembersRoute,
  MySyndicateRoute: MySyndicateRoute,
  NftRoute: NftRoute,
  NftsRoute: NftsRoute,
  ProtocolHealthRoute: ProtocolHealthRoute,
  RanksRoute: RanksRoute,
  ReferralRoute: ReferralRoute,
  RegistryRoute: RegistryRoute,
  RiskRoute: RiskRoute,
  RoadmapRoute: RoadmapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TokenRoute: TokenRoute,
  TokenomicsRoute: TokenomicsRoute,
  TransparencyRoute: TransparencyRoute,
  VaultRoute: VaultRoute,
  WhitepaperRoute: WhitepaperRoute,
  ApiChatRoute: ApiChatRoute,
  MilestoneIdRoute: MilestoneIdRoute,
  WalletAddressRoute: WalletAddressRoute,
  ApiOgHealthRoute: ApiOgHealthRoute,
  ApiPublicProtocolHealthRoute: ApiPublicProtocolHealthRouteWithChildren,
  XTxHashRoute: XTxHashRoute,
  ApiPublicIndexerHealthRoute: ApiPublicIndexerHealthRoute,
  ApiPublicOgMilestoneIdRoute: ApiPublicOgMilestoneIdRoute,
  ApiPublicOgWalletAddressRoute: ApiPublicOgWalletAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
